package asterix;



/*
 * About.java
 *
 * Created on Jan 1, 2008, 3:08:35 AM
 */

import javax.swing.ImageIcon;

/**
 *
 * @author Akhilesh
 */
public class About extends javax.swing.JDialog {

    private Editor mtp;
 
    ImageIcon icon = new ImageIcon(this.getClass().getResource("/asterix/image/splace.png"));
    
    /**
     * Creates new form About
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
 
        initComponents();
         //   setSize(icon.getIconWidth() + 10, icon.getIconHeight() + 30);
           
        this.setIconImage(new ImageIcon(this.getClass().getResource("/asterix/image/favicon.png")).getImage());//new ImageIcon("/playerApp/Image/play.png").getImage()
        this.setTitle("About");
        this.setLocation(400, 100);        
    }

    About(Editor aThis) {
        mtp = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(191, 205, 219));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asterix/image/splace.png"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(" Welcome to Asterix IDE 1.5.5 \n\n Asterix IDE is a full-featured IDE (Integrated Development\n Environment) aiming to make the programmers work in a nice\n programming environment offering everything they would \n ever need from a program of that kind.\n\n Asterix IDE is especially designed to ease the work of \n Java and web developers by providing them with an \n intuitive IDE that they can use to write, compile and run  their code. An IDE is much more than a text editor. \n Asterix IDE offers superior support for JAVA and HTML \n developers, providing comprehensive editors and tools.\n\n Use for anyone as long as it is acknowldedged to me Please\n dont reuse this code without prior notice. If you have any\n enquiries please do not hesitate to email us.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Description", jScrollPane1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText(" Name: Asterix IDE\n Since: Mar 22, 2013, 8:26:30 PM \n Version 1.5.5\n SDK Version: Java 1.7.0\n Author: Akhilesh Dubey\n E-mail: 2akhileshdubey@gmail.com\n Website: https://www.facebook.com/akhilesh006");
        jScrollPane2.setViewportView(jTextArea2);

        jTabbedPane1.addTab("Information", jScrollPane2);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText(" This program is Freeware Licence version.\n\n Available online under:\n http://sourceforge.net/projects/asterixide/");
        jScrollPane3.setViewportView(jTextArea3);

        jTabbedPane1.addTab("License", jScrollPane3);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String... args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                About dialog = new About(new javax.swing.JFrame(), true);
                dialog.setDefaultCloseOperation(About.DISPOSE_ON_CLOSE);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
